### ISSUE TITLE
Absolute Speed

### ISSUE THREAD

**Issue by seark** [ideka/RacingMeterPublic#1]
I just started using the module and noticed that the speeds seem to be relative to the used mounts maximum. It would be great, if it was possible to switch to absolute speeds and maybe enable the speedometer for the other mounts as well. I would have made the changes myself but I think you didn't publish the sources of your module.

**Comment by ideka** [comment]
You can measure absolute speed by enabling debug mode (set a keybind for it in the settings first). Speedometers are not meant to show absolute speed.
I tried making speedometers for the other mounts too, but most are too simple to warrant one. The reading would almost always be at one of two or three spots, and almost never anywhere in between. I'll think about it though.
